baseURL: https://buwa-jamstack.github.io/vacatures/
title: BuWa Vacatures
theme: buwanieuws
markup:
  goldmark:
    renderer:
      unsafe: true
      hardWraps: true

outputs:
  section:
    - json
    - html
  home:
    - json
    - html
  post:
    - json
    - html
  taxonomy:
    - json
    - html
  taxonomyTerm:
    - json
    - html

