hugover: 0.101.0
serve:
  - key: default
    config: config.yaml

build:
  - key: default
    config: config.yaml
menu:
  - key: content
    title: Content
    menuItems:
      - key: post
      - key: frontpage
  - key: settings
    title: Settings
    menuItems:
      - key: mainConfig

singles:

  - key: frontpage
    title: Frontpage
    file: content/_index.md
    dataformat: yaml
    fields:
      - key: info
        type: info
        content: "Toon voorbeeld http://localhost:13131/vacatures/"
      - key: title
        title: Title
        type: string
      - key: mainContent
        title: Main content
        type: markdown

      - key: images
        type: bundle-manager
        path: ./images
        extensions:
          - svg
          - png
          - jpg
          - gif
        fields:
          - key: thumb
            title: Thumb
            type: bundle-image-thumbnail

  - key: mainConfig
    title: Site Configuration
    file: config.yaml
    fields:
      - key: title
        title: Site Title
        type: string
        tip: Your page title.
      - key: baseURL
        title: Base URL
        type: string
        tip: Your site URL.
